{
    'name': 'ALTANMYA Converting Money Into Words',
    'version': '1.0',
    'summary': 'Converting Money Into Words in Invoice and Accounting',
    'description': "Convert number of total price to words in arabic & english.",
    'category': 'Accounting/Accounting',
    'author': 'ALTANMYA - TECHNOLOGY SOLUTIONS',
    'company': 'ALTANMYA - TECHNOLOGY SOLUTIONS Part of ALTANMYA GROUP',
    'website': "https://tech.altanmya.net",
    'depends': ['account', 'sale', 'base'],
    'data': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}