{
    'name': 'ALTANMYA Invoice Sequence Line',
    'version': '1.0', 
    'summary': 'Invoice Sequence Line',
    'description': "Add Automatice Sequence Line for Invoice Line",
    'category': 'Accounting/Accounting',
    'author': 'ALTANMYA - TECHNOLOGY SOLUTIONS',
    'company': 'ALTANMYA - TECHNOLOGY SOLUTIONS Part of ALTANMYA GROUP',
    'website': "https://tech.altanmya.net",
    'depends': ['account_accountant'],
    'data': ['security/ir.model.access.csv'],
    'demo': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
